package com.agorasim.meat;

import net.minecraft.entity.effect.StatusEffectInstance;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.item.FoodComponent;

public class Food {

    public static final FoodComponent COAL = (new FoodComponent.Builder()).hunger(8).saturationModifier(1.8F).statusEffect(new StatusEffectInstance(StatusEffects.NIGHT_VISION, 1200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HASTE, 600, 1), 1).alwaysEdible().build();
    public static final FoodComponent COPPER = (new FoodComponent.Builder()).hunger(8).saturationModifier(1.8F).statusEffect(new StatusEffectInstance(StatusEffects.SPEED, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.WEAKNESS, 100, 0), 1).alwaysEdible().build();
    public static final FoodComponent EMERALD = (new FoodComponent.Builder()).hunger(8).saturationModifier(1.8F).statusEffect(new StatusEffectInstance(StatusEffects.HERO_OF_THE_VILLAGE, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 600, 0), 1).alwaysEdible().build();
    public static final FoodComponent LAPIS = (new FoodComponent.Builder()).hunger(8).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.LUCK, 600, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 1200, 0), 1).alwaysEdible().build();
    public static final FoodComponent OBSIDIAN = (new FoodComponent.Builder()).hunger(8).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 1200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 300, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 300, 0), 1).alwaysEdible().build();
    public static final FoodComponent DIAMOND = (new FoodComponent.Builder()).hunger(14).saturationModifier(2.5F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 600, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 2400, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 2400, 2), 1).alwaysEdible().build();
    public static final FoodComponent NETHERITE = (new FoodComponent.Builder()).hunger(20).saturationModifier(2.5F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 2400, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 2400, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 2400, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 4800, 2), 1).alwaysEdible().build();
    public static final FoodComponent IRON = (new FoodComponent.Builder()).hunger(9).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 600, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 1200, 0), 1).alwaysEdible().build();
    public static final FoodComponent GOLD = (new FoodComponent.Builder()).hunger(9).saturationModifier(2F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 1200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.JUMP_BOOST, 1200, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.INVISIBILITY, 1200, 0), 1).alwaysEdible().build();

    public static final FoodComponent ECOAL = (new FoodComponent.Builder()).hunger(12).saturationModifier(2.7F).statusEffect(new StatusEffectInstance(StatusEffects.NIGHT_VISION, 6000, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HASTE, 2400, 4), 1).alwaysEdible().build();
    public static final FoodComponent ECOPPER = (new FoodComponent.Builder()).hunger(12).saturationModifier(2.7F).statusEffect(new StatusEffectInstance(StatusEffects.SPEED, 6000, 2), 1).alwaysEdible().build();
    public static final FoodComponent EEMERALD = (new FoodComponent.Builder()).hunger(12).saturationModifier(2.7F).statusEffect(new StatusEffectInstance(StatusEffects.HERO_OF_THE_VILLAGE, 2400, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 3600, 2), 1).alwaysEdible().build();
    public static final FoodComponent ELAPIS = (new FoodComponent.Builder()).hunger(12).saturationModifier(3F).statusEffect(new StatusEffectInstance(StatusEffects.LUCK, 2400, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 6000, 2), 1).alwaysEdible().build();
    public static final FoodComponent EOBSIDIAN = (new FoodComponent.Builder()).hunger(12).saturationModifier(3F).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 2400, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 1200, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 1200, 0), 1).alwaysEdible().build();
    public static final FoodComponent EDIAMOND = (new FoodComponent.Builder()).hunger(20).saturationModifier(3.7F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 2400, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 1800, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.WATER_BREATHING, 6000, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 3600, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 6000, 2), 1).alwaysEdible().build();
    public static final FoodComponent ENETHERITE = (new FoodComponent.Builder()).hunger(20).saturationModifier(3.7F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 6000, 4), 1).statusEffect(new StatusEffectInstance(StatusEffects.STRENGTH, 2400, 4), 1).statusEffect(new StatusEffectInstance(StatusEffects.FIRE_RESISTANCE, 6000, 0), 1).statusEffect(new StatusEffectInstance(StatusEffects.HEALTH_BOOST, 6000, 4), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 12000, 2), 1).alwaysEdible().build();
    public static final FoodComponent EIRON = (new FoodComponent.Builder()).hunger(14).saturationModifier(3F).statusEffect(new StatusEffectInstance(StatusEffects.ABSORPTION, 3600, 2), 1).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 1200, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.RESISTANCE, 2400, 1), 1).alwaysEdible().build();
    public static final FoodComponent EGOLD = (new FoodComponent.Builder()).hunger(14).saturationModifier(3F).statusEffect(new StatusEffectInstance(StatusEffects.REGENERATION, 2400, 1), 1).statusEffect(new StatusEffectInstance(StatusEffects.JUMP_BOOST, 2400, 9), 1).statusEffect(new StatusEffectInstance(StatusEffects.INVISIBILITY, 2400, 0), 1).alwaysEdible().build();

}
